---
syntax: manifest_v1
description: A Grafana dashboard integration app
icon: https://playground.srly.io/edge-apps/grafana/static/img/icon.svg
author: Screenly, Inc.
ready_signal: true
settings:
  dashboard_id:
    type: string
    title: Dashboard ID
    optional: false
    help_text:
      properties:
        help_text: The unique ID of the Grafana dashboard
        type: oauth:grafana:dashboard_id
      schema_version: 1
  domain:
    type: string
    title: Grafana Domain
    optional: false
    help_text:
      properties:
        help_text: The Grafana domain (e.g., someone.grafana.net)
        type: string
      schema_version: 1
  refresh_interval:
    type: string
    default_value: '60'
    title: Refresh Interval
    optional: true
    help_text:
      properties:
        help_text: The interval in seconds to refresh the dashboard image
        type: number
      schema_version: 1
  service_access_token:
    type: secret
    title: Service Account Token
    optional: false
    help_text:
      properties:
        help_text: The Grafana service account token used to authenticate dashboard rendering requests
        type: string
      schema_version: 1
