---
syntax: manifest_v1
id: 01KFMNBR33GFGWY5TW8VNZND5X
description: A Grafana dashboard integration app
icon: https://playground.srly.io/edge-apps/grafana/static/img/icon.svg
author: Screenly, Inc.
ready_signal: true
settings:
  access_token:
    type: secret
    title: Access Token
    optional: true
    help_text:
      properties:
        help_text: For testing only. In production, the access token should be fetched dynamically via the API.
        type: oauth:grafana:access_token
      schema_version: 1
  dashboard_id:
    type: string
    title: Dashboard ID
    optional: false
    help_text:
      properties:
        help_text: The unique ID of the Grafana dashboard
        type: oauth:grafana:dashboard_id
      schema_version: 1
  display_errors:
    type: string
    default_value: 'false'
    title: Display Errors
    optional: true
    help_text:
      properties:
        advanced: true
        help_text: For debugging purposes to display errors on the screen.
        type: boolean
      schema_version: 1
  refresh_interval:
    type: string
    default_value: '60'
    title: Refresh Interval
    optional: true
    help_text:
      properties:
        help_text: The interval in seconds to refresh the dashboard image
        type: number
      schema_version: 1
